<a href="https://colab.research.google.com/github/Shravan1711/Data-Science-Assignments/blob/main/Numpy%20Library%20Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
import numpy as np

In [53]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [54]:
a=np.array([10])
b=np.array([1,2,3])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [55]:
a

array([10])

In [45]:
b

array([1, 2, 3])

In [46]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [48]:
a.shape

(1,)

In [49]:
b.shape

(3,)

In [50]:
c.shape

(2, 3)

In [51]:
d.shape

(2, 2, 3)

In [60]:
type(c)

numpy.ndarray

In [59]:
type(d)

numpy.ndarray

In [63]:
type('a')

str

In [64]:
type('b')

str

In [65]:
len(b)

3

In [79]:
l1=[10,20,30]
l2=[40,50,60]
l3=l1
l4=l2

In [80]:
l1

[10, 20, 30]

In [81]:
l2

[40, 50, 60]

In [85]:
list1=np.array(l1)
list2=np.array(l2)
print(list1*list2)

[ 400 1000 1800]


In [86]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [97]:
x = np.arange(1,17)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [99]:
x.reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [100]:
x.reshape(2,4,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [101]:
x.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [102]:
a = [2,4,6,8,10,12,14,16]
a

[2, 4, 6, 8, 10, 12, 14, 16]

In [105]:
print(a[3])

8


In [108]:
a[7]

16

In [106]:
a[5]

12

In [111]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [113]:
a[2,2]

9

In [114]:
b = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [115]:
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [116]:
b[1,0,2]

9

In [122]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr[:-7]

array([1, 2, 3, 4, 5])

In [119]:
arr[5:]

array([ 6,  7,  8,  9, 10, 11, 12])

In [120]:
arr[0:5]

array([1, 2, 3, 4, 5])

In [124]:
arr[1:7]

array([2, 3, 4, 5, 6, 7])

In [125]:
arr[0:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [133]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [127]:
a[2,0:]

array([7, 8, 9])

In [137]:
a[0:,2]

array([3, 6, 9])

In [134]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [138]:
a[0:,1]

array([2, 5, 8])

In [153]:
x1=np.array([1,2,3,4])
x2=x1.copy()

In [154]:
print(x1,x2)

[1 2 3 4] [1 2 3 4]


In [155]:
x2[0]=10

In [156]:
print(x1,x2)

[1 2 3 4] [10  2  3  4]


In [145]:
x1=np.array([1,2,3])
x3=x1.view()

In [146]:
print(x1,x3)

[1 2 3] [1 2 3]


In [152]:
x3[0]=100
x1,x3

(array([100,   2,   3]), array([100,   2,   3]))

In [159]:
x4=x1.copy()
x4[3]=900

In [160]:
print(x1,x4)

[1 2 3 4] [  1   2   3 900]


In [162]:
np.hstack((x1,x4))

array([  1,   2,   3,   4,   1,   2,   3, 900])

In [163]:
np.vstack((x1,x4))

array([[  1,   2,   3,   4],
       [  1,   2,   3, 900]])

In [167]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])

In [168]:
np.concatenate((arr1,arr2),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [169]:
np.concatenate((arr1,arr2),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [171]:
np.append(arr2,arr1,axis=0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [172]:
x1

array([1, 2, 3, 4])

In [174]:
x4

array([  1,   2,   3, 900])

In [175]:
np.insert(x1,3,x4,axis=0)

array([  1,   2,   3,   1,   2,   3, 900,   4])

In [176]:
x2

array([10,  2,  3,  4])

In [177]:
np.delete(x2,1,axis=0)

array([10,  3,  4])